plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/certs/page:num/"
timezone: America/New_York
include:
  - assets
  - assets/pdfs


# Site settings
title: Lou Spironello
description: Professional portfolio and certifications

# Use HTML files as pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - assets/resumes
